# Generated by Django 4.2.4 on 2023-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_blogpost_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
